### ISSUE TITLE
Unicode characters on settings.py help strings

### ISSUE THREAD

**Issue by dballesg** [trentinfrederick/name-panel#5]
Hi,

Trying to generate the .pypredef files for eclipse with your add-on installed I was getting an error that will stop the generation of such files.

After step debug the script from here: https://github.com/mutantbob/pycharm-blender, it was failing on the view3d.reset_name_panel_settings arguments. 

I found that you have the symbol  → on several lines of the settings.py.

Sadly the .pypredef generator is not guarded against unicode characters on scripts, so it could be possible that you change it fro example for the -> ascci characters? 

Cheers, 
David.

**Comment by trentinfrederick** [comment]
Sorry just noticed the opened issue, I prefer the arrows so instead I just made it ascii compatible, thanks for letting me know :)

**Comment by dballesg** [comment]
Thanks proxe. I prefer your solution too.! :)

2016-06-13 9:56 GMT+02:00 proxe <notifications@github.com>:
